// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmaflow7.Data;

#nullable disable

namespace Pharmaflow7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820003803_AddEmailConfirmationFields")]
    partial class AddEmailConfirmationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified designer file - the full model would be too large
            // The actual migration only adds the EmailConfirmedAt column to AspNetUsers table
#pragma warning restore 612, 618
        }
    }
}